### ISSUE TITLE
CLI executable

### ISSUE THREAD

**Issue by jaimergp** [andresginera/pgaudi#1]
`setup.py` allows to specify "entry points" so you can create CLI executables. [Read here](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point)

For this to work, you should refactor `main.py` so the `argparse` stuff is in a function itself (let's say, `parse_cli`) that returns the parsed namespace. Also `main()` should call `parse_cli`. Ideally you should have something like this:

```
def parse_cli():
    # use argparse to parse cli

def run():
    # your current main function, which contains the main logic of the program

def main():
    # the cli entry point!
    args = parse_cli()
    run(args.arg1, args.arg2, arg3=args.arg3... etc)

if __name__ == '__main__':
    main()
```

**Comment by andresginera** [comment]
Resolved by commit <commit a50ecbe>

**Comment by andresginera** [comment]
Resolved by commit <a50ecbe>

**Comment by andresginera** [comment]
Resolved by commit https://github.com/andresginera/pgaudi/commit/a50ecbe6ecf0ce5d4545f4a8b2a11e85270f47.

**Comment by jaimergp** [comment]
This (addressing commits responsible for one particular change) is one of the reasons why we insist on the trope "commit often". That commit had a lot of changes not related to this particular thing. Next time, try to commit once per issue (or at least "change").
