### ISSUE TITLE
Use explicit imports

### ISSUE THREAD

**Issue by jaimergp** [andresginera/pgaudi#2]
Now you are using _implicit relative_ imports, such as [here](https://github.com/andresginera/pgaudi/blob/master/pgaudi/main.py#L20). This has a problem! If you (or any users) happen to install a package named `parallel`, it could shadow your module (or the other way around). The correct way is to use explicit imports:

```
from . import parallel
```

To enforce this rule in Python 2 (default in Py3), you need to use this `__future__` import at the beginning of the file:

```
from __future__ import absolute_import
```

[Read this](https://realpython.com/absolute-vs-relative-python-imports/) for more details

**Comment by andresginera** [comment]
Resolved by commit <https://github.com/andresginera/pgaudi/commit/c6f032f78ab55ae4f9dee547a8e0a590a618d90b>.
