### ISSUE TITLE
In-place modification of mutables

### ISSUE THREAD

**Issue by jaimergp** [andresginera/pgaudi#3]
Careful with [this type](https://github.com/andresginera/pgaudi/blob/master/pgaudi/similarity.py#L71) of procedure. YIn Python, variables are not copied between functions, they are passed. So, if you modify this list, the changes will be available in every other part of the code. This can be tricky to debug if it produces problems, so a general recommendation is to create a copy of the list at the beginning of the function and the return the modified copy.

**Comment by andresginera** [comment]
Resolved by commit <https://github.com/andresginera/pgaudi/commit/0678f2142ecf3e62250580ac702c310fbe987a93>.
