### ISSUE TITLE
Test behavior of KeyboardInterrupt exceptions

### ISSUE THREAD

**Issue by jaimergp** [andresginera/pgaudi#4]
What would happen if the user presses `Ctrl+C`?

**Comment by andresginera** [comment]
With the last commit, now, when the user presses `Ctrl+C` the program interrupts correctly all the gaudi's processes.

Resolved by commit <https://github.com/andresginera/pgaudi/commit/02d79b974e5b89a69f3b3133d6adae79019d2141>.
